#!/bin/bash
SR_COMMAND_DESC="Trigger the build process using the Swift Package Manager"

source /etc/profile

SR_TRIPLE=armv7-none-linux-androideabi
SR_ARCH=ARMV7A

TOOLCHAIN="SR_ANDROID_${SR_ARCH}_TOOLCHAIN"
SDK="SR_ANDROID_${SR_ARCH}_SDK"
GCC_LIB="SR_ANDROID_${SR_ARCH}_GCC_LIB"

####### SwiftGlibc HAS A HARDCODED PATH

cat /root/swift-install/usr/lib/swift/android/armv7/glibc.modulemap \
	| sed 's/\/root\/ndk\/android-ndk-r14b\/platforms\/android-21\/arch-arm\//\/root\/android-standalone-toolchain\/sysroot/g' \
	> /root/swift-install/usr/lib/swift/android/armv7/glibc.modulemap

####### /SwiftGlibc HAS A HARDCODED PATH

####### locale.h DUPLICATED

rm /root/android-standalone-toolchain/sysroot/usr/local/include/locale.h
rm /root/android-standalone-toolchain/sysroot/usr/local/include/xlocale.h

####### /locale.h DUPLICATED

####### CREATING android-destination.json FOR SWIFT PM

cat > "/root/android-destination.json" <<EOF
{
    "version": 1,
    "sdk": "${!SDK}",
    "toolchain-bin-dir": "$SR_SWIFT_BIN",
    "target": "$SR_TRIPLE",
    "dynamic-library-extension": "so",
    "extra-cc-flags": [
        "-fPIC"
    ],
    "extra-swiftc-flags": [
        "-use-ld=gold", "-tools-directory", "${!TOOLCHAIN}/bin", "-L${!SDK}/usr/lib"
    ],
    "extra-cpp-flags": [
    ]
}
EOF

#######

$SR_SWIFT_BIN/swift build \
    -Xlinker -fpie -Xlinker -shared \
    -Xlinker -L${!GCC_LIB} \
    -Xlinker -L${!SDK}/usr/lib \
    -Xlinker ${!TOOLCHAIN}/lib/libatomic.a \
    --destination /root/android-destination.json \
    $@
