#!/bin/bash
SR_COMMAND_DESC="Trigger the build process using the Swift Package Manager"

source /etc/profile

SR_TRIPLE=armv7-none-linux-androideabi
SR_ARCH=ARMV7A

TOOLCHAIN="SR_ANDROID_${SR_ARCH}_TOOLCHAIN"
SDK="SR_ANDROID_${SR_ARCH}_SDK"
GCC_LIB="SR_ANDROID_${SR_ARCH}_GCC_LIB"

####### SwiftGlibc HAS A HARDCODED PATH

cat /root/swift-install/usr/lib/swift/android/armv7/glibc.modulemap \
	| sed 's/\/root\/ndk\/android-ndk-r14b\/platforms\/android-21\/arch-arm\//\/root\/android-standalone-toolchain\/sysroot/g' \
	> /root/swift-install/usr/lib/swift/android/armv7/glibc.modulemap

####### /SwiftGlibc HAS A HARDCODED PATH

####### locale.h DUPLICATED

rm /root/android-standalone-toolchain/sysroot/usr/local/include/locale.h
rm /root/android-standalone-toolchain/sysroot/usr/local/include/xlocale.h

####### /locale.h DUPLICATED

$SR_SWIFT_BIN/swift build \
    -Xswiftc -target -Xswiftc $SR_TRIPLE \
    -Xswiftc -tools-directory -Xswiftc ${!TOOLCHAIN}/bin \
    -Xswiftc -sdk -Xswiftc ${!SDK} \
    -Xswiftc -L${!SDK}/usr/lib \
    -Xcc -target -Xcc $SR_TRIPLE \
    -Xcc --sysroot=${!SDK} \
    -Xcc -fPIC -Xlinker -fpie -Xlinker -shared \
    -Xlinker -fuse-ld=ANDROID_TARGET \
    -Xlinker -L${!GCC_LIB} \
    -Xlinker -L${!SDK}/usr/lib \
    -Xlinker ${!TOOLCHAIN}/lib/libatomic.a \
    $@
